export const CLIENT_MASTER_LIST = [
  {
    emeraldId: "a9ec618a-a3de-4398-b",
    clientName: "Euland China Company",
    clientId: "001Rb000000w5JAIAY",
    sourceSystem: "SFDC",
    createdBy: "William J",
    updatedBy: "William J",
    isConflict: false,
  },
  {
    emeraldId: "037827ad-3676-4a1a-9",
    clientName: "A & G International trade",
    clientId: "0015c00002E41TqAAJ",
    sourceSystem: "SFDC",
    createdBy: "Henry A",
    updatedBy: "Henry A",
    isConflict: true,
  },
  {
    emeraldId: "c8de00bd-897e-421a-8",
    clientName: "A.S.Adventure EU",
    clientId: "001Rb000000tcXlIAI",
    sourceSystem: "SFDC",
    createdBy: "Amelia",
    updatedBy: "Amelia",
    isConflict: false,
  },
  {
    emeraldId: "27059ef1-8316-4f38-8",
    clientName: "ABC DISTRIBUTION LLC",
    clientId: "001Rb000000fcVxIAI",
    sourceSystem: "SFDC",
    createdBy: "Sofia Martinez",
    updatedBy: "Sofia Martinez",
    isConflict: true,
  },
  {
    emeraldId: "c945ab66-e147-41ae-a",
    clientName: "ABC Liquidation Inc.",
    clientId: "001Rb000000rXFZIA2",
    sourceSystem: "SFDC",
    createdBy: "Mohammad Khan",
    updatedBy: "Mohammad Khan",
    isConflict: false,
  },
  {
    emeraldId: "e0885c5a-cf61-4b0e-8",
    clientName: "AD HOC INC",
    clientId: "001Rb000000fhsDIAQ",
    sourceSystem: "SFDC",
    createdBy: "Anna Novák",
    updatedBy: "Anna Novák",
    isConflict: false,
  },
  {
    emeraldId: "3bc235d0-2986-4097-a",
    clientName: "AFH Senior Care",
    clientId: "001Rb000000hQ0vIAE",
    sourceSystem: "SFDC",
    createdBy: "Diego Lopez",
    updatedBy: "Diego Lopez",
    isConflict: false,
  },
  {
    emeraldId: "5b7dd372-9574-4bba-a",
    clientName: "ALEA Sportswear",
    clientId: "0015c00002E41TtAAJ",
    sourceSystem: "SFDC",
    createdBy: "Maria Silva",
    updatedBy: "Maria Silva",
    isConflict: false,
  },
  {
    emeraldId: "318cc43a-4c1a-46c4-a",
    clientName: "ALI ORHAN",
    clientId: "001Rb000000g53NIAQ",
    sourceSystem: "SFDC",
    createdBy: "Ahmed Al-Mansouri",
    updatedBy: "Ahmed Al-Mansouri",
    isConflict: false,
  },
  {
    emeraldId: "8099b1cb-60d7-42e8-8",
    clientName: "ALLANS GENERAL SHOW",
    clientId: "0015c00002E41TwAAJ",
    sourceSystem: "SFDC",
    createdBy: "Chihiro Yamamoto",
    updatedBy: "Chihiro Yamamoto",
    isConflict: false,
  }
];

export const DESTINATION_SYSTEM_OPTIONS = [
  {value: 'salesforce', label: 'Salesforce'},
  {value: 'a2Z', label: 'a2Z'},
  {value: 'TMM', label: 'TMM'},
  {value: 'Zoura', label: 'Zoura'},
  {value: 'ASQW', label: 'ASQW'},
  {value: 'ASAW', label: 'ASAW'},
];
