/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api83d15cb6",
            "endpoint": "https://265mmwe9i3.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-north-1:8db0ba9c-6a26-4bee-be13-b5154ace1035",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_sDVmTv48c",
    "aws_user_pools_web_client_id": "5bop9gg9cfoun5qig0jb7t2g7t",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
